### ISSUE TITLE
Missing exposure

### ISSUE THREAD

**Issue by Zamiell** [mafredri/go-trueskill#4]
According to trueskill.org, a leaderboard should be sorted by something called "rating exposure" (as opposed to mu). This was a big surprise to me, as before reading this I had been previously been sorting by mu, which I take to mean the "matchup rating".

1) What exactly is rating exposure? The trueskill.org site doesn't say.
2) How are you supposed to calculate exposure?
3) Can the go-trueskill library calculate exposure? The docs don't have a mention of this.

**Comment by mafredri** [comment]
I think that's a term invented by trueskill.org, keep in mind that it's not an official source of information regarding TrueSkill, it's a popular python library that implements the algorithm.

You can use [`Config.TrueSkill`](https://godoc.org/github.com/mafredri/go-trueskill#Config.TrueSkill) for the same effect. That function returns the conservative estimate of the players skill. The `mu` variable is important for tracking the players skill, but it's only used for calculations and doesn't provide the whole picture about the players skill.

**Comment by Zamiell** [comment]
ok, thank you!
